### ISSUE TITLE
detected by EDR due to traffic: Botnet

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [rapid7/metasploit-payloads#508] opened 2021-11-12 07:57 UTC
How is meterpreter detected as Botnet?
Even if https and custom certificates are used. Even if the endpoint is localhost:443.

Http on the other hand is not detected (at least in my specific case) - so is that a telemetry based thing? How would that work and what could be done in order to generically prevent detection via that approach?

**Comment by smcintyre-r7** [comment] 2021-12-28 16:10
Closing this as a duplicate of https://github.com/rapid7/metasploit-framework/issues/15876.

**Closed by smcintyre-r7** 2021-12-28 16:10 UTC
Labels: question
