### ISSUE TITLE
Payload creation process not proceeding

### ISSUE THREAD

**Issue by Samshow-cyber** [rapid7/metasploit-payloads#544] opened 2022-02-24 23:50 UTC
I solved the apktool issue after making some researches. But I have another issue ongoing.

I'm trying to add payload to an apk file. I followed the normal command format and processed the command in the CMD. This is what I got:

```
Using apk template: theapk.apk
[-] No platform was selected, choosing Msf::module::platform::Android from #the payload
[-] No arch selected, selecting arch: dalvik from payload
```

And after that, nothing more... the command prompt it still processing (still blinking the white dash)

Please why is this happening? Please help!

**Comment by Samshow-cyber** [comment] 2022-02-25 10:58
Anyone?

**Comment by bcoles** [comment] 2022-02-26 14:26
Dupe of #543

**Closed by bcoles** 2022-02-26 14:26 UTC
